version: "3.9"

services:
  db:
    image: postgres:15
    environment:    
      ENV_FILE: .env.docker
      POSTGRES_USER: cibernodo
      POSTGRES_PASSWORD: cibernodo123
      POSTGRES_DB: cibernodo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      ENV_FILE: .env.docker
    env_file:
      - .env.docker

volumes:
  pgdata: